# Generated by Django 4.1.3 on 2022-12-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[(None, 'Choose country'), ('Россия', 'Россия'), ('US', 'US')], max_length=20),
        ),
    ]
