# Generated by Django 4.1.3 on 2022-12-08 12:08

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_gallery_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to=shop.models.get_upload_path),
        ),
    ]
